// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uucgnwvjumjmhxtvrdmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1Y2dud3ZqdW1qbWh4dHZyZG15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxMjMwMDIsImV4cCI6MjA1NTY5OTAwMn0.eaWnDE8S7_tr21Xa-F_TRIAEodN-qdJeQjxNxJdgg3k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);